In [ ]:
from google.colab import  drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np
from pandas import read_csv
from sklearn.preprocessing import MinMaxScaler
import random

In [ ]:
name=["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w"]
data=read_csv("/content/drive/My Drive/sc_lab/Heart_Dataset.csv",names=name)
scaler = MinMaxScaler()
scaler.fit(data)
data

    a  b  c  d  e  f  g  h  i  j  k  l  m  n  o  p  q  r  s  t  u  v  w
0   1  0  0  0  1  0  0  0  1  1  0  0  0  1  1  0  0  0  0  0  0  0  0
1   1  0  0  1  1  0  0  0  1  1  0  0  0  1  1  0  0  0  0  0  0  0  1
2   1  1  0  1  0  1  0  0  1  0  1  0  0  1  0  0  0  0  0  0  0  0  0
3   1  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  1  1  1
4   1  0  0  0  0  0  0  0  1  0  0  0  0  1  0  1  1  0  0  0  0  0  0
.. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..
75  0  1  0  0  0  1  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0
76  0  1  0  0  0  1  1  0  0  1  1  0  0  0  1  0  0  0  0  1  1  0  0
77  0  1  0  0  0  1  0  0  0  0  1  0  0  0  0  0  0  0  0  1  0  0  0
78  0  0  0  1  1  0  0  1  0  0  0  0  1  1  1  0  0  0  0  0  0  1  1
79  0  1  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0

[80 rows x 23 columns]

In [ ]:
d1=data[["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v"]]
d2=data["w"]
d1=np.array(d1)
d2=np.array(d2)
data=np.array(data)
data

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 1],
       [1, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 1],
       [0, 1, 0, ..., 0, 0, 0]])

In [ ]:
n=len(data[0])-1
n

22

In [ ]:
def fun(data,N,error,weight,bias,l):
  predict=[0 for i in range(N)]
  
  for i in range(N):
    val=0
    for j in range(n):
      val+=data[i][j]*weight[j]
    val+=bias

    if(val<=0):
      predict[i]=0
    else:
      predict[i]=1

    error[i]=data[i][n]-predict[i]

    for j in range(n):
      if(data[i][j]!=0):
        weight[j]=weight[j]+l*error[i]

  return weight

In [ ]:
def classification_report(cm):
    accuracy = 0
    total = np.sum(cm)
    diagonal = np.sum(np.diag(cm))
    accuracy=(diagonal/total)*100
    print("Accuracy : => ",(diagonal/total)*100)
    return accuracy

In [ ]:
block=int(len(data)/10)
# print(block)
M=[[ 0 for i in range(2)] for i in range(2)]
for i in range(10):

  L=0.2
  bias=0
  temp_x_data=[]
  temp_y_data=[]
  
  x_test=[]
  y_test=[]
  

  point=[]
  for j in range(block):
    point.append(block*i+j)

  
  for j in range(len(data)):
    if(j in point):
      x_test.append(d1[j])
      y_test.append(d2[j])
    else:
      temp_x_data.append(d1[j])
      temp_y_data.append(d2[j])


  
  matrix=[[0 for i in range(2)]for i in range(2)]

  weight=[1/n for i in range(n)]
  error=[1 for i in range(len(temp_x_data))]
  
  max_itr=500
  while(max_itr):
    w=fun(data,len(temp_x_data),error,weight,bias,L)
    weight=w
    max_itr-=1

  for j in range(len(x_test)):
    val=0
    for k in range(n):
      val+=x_test[j][k]*weight[k]
    val+=bias

    if(val<=0):
      matrix[y_test[j]][0]+=1
    else:
      matrix[y_test[j]][1]+=1

  for p in range(2):
    for q in range(2):
      M[p][q]+=matrix[p][q]
  print("Fold ",i+1)
  print(matrix)
  accu=classification_report(matrix)
print()
print("Final confusion matrix")
print(M)
print()
print("Average accuracy=>",classification_report(M))

Fold  1
[[3, 0], [4, 1]]
Accuracy : =>  50.0
Fold  2
[[2, 0], [3, 3]]
Accuracy : =>  62.5
Fold  3
[[6, 0], [2, 0]]
Accuracy : =>  75.0
Fold  4
[[5, 1], [2, 0]]
Accuracy : =>  62.5
Fold  5
[[4, 0], [2, 2]]
Accuracy : =>  75.0
Fold  6
[[5, 1], [2, 0]]
Accuracy : =>  62.5
Fold  7
[[5, 1], [1, 1]]
Accuracy : =>  75.0
Fold  8
[[7, 0], [1, 0]]
Accuracy : =>  87.5
Fold  9
[[7, 0], [1, 0]]
Accuracy : =>  87.5
Fold  10
[[7, 0], [1, 0]]
Accuracy : =>  87.5

Final confusion matrix
[[51, 3], [19, 7]]

Accuracy : =>  72.5
Average accuracy=> 72.5